import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ResponsiveAreaBump } from '@nivo/bump'
import Navbar from "./navbar";

const data = [
    {
        id: "JavaScript",
        data: [
            {
                x: 2000,
                y: 13
            },
            {
                x: 2001,
                y: 24
            },
            {
                x: 2002,
                y: 16
            },
            {
                x: 2003,
                y: 15
            },
            {
                x: 2004,
                y: 29
            },
            {
                x: 2005,
                y: 23
            }
        ]
    },
    {
        id: "Typescript" ,
        icon:"load.gif",
        data: [
            {
                x: 2000,
                y: 27
            },
            {
                x: 2001,
                y: 28
            },
            {
                x: 2002,
                y: 30
            },
            {
                x: 2003,
                y: 25
            },
            {
                x: 2004,
                y: 12
            },
            {
                x: 2005,
                y: 17
            }
        ]
    },
    {
        id: "TypeScript",
        data: [
            {
                x: 2000,
                y: 18
            },
            {
                x: 2001,
                y: 23
            },
            {
                x: 2002,
                y: 19
            },
            {
                x: 2003,
                y: 18
            },
            {
                x: 2004,
                y: 14
            },
            {
                x: 2005,
                y: 10
            }
        ]
    },
    {
        id: "Elm",
        data: [
            {
                x: 2000,
                y: 25
            },
            {
                x: 2001,
                y: 16
            },
            {
                x: 2002,
                y: 26
            },
            {
                x: 2003,
                y: 26
            },
            {
                x: 2004,
                y: 16
            },
            {
                x: 2005,
                y: 10
            }
        ]
    },
    {
        id: "CoffeeScript",
        data: [
            {
                x: 2000,
                y: 27
            },
            {
                x: 2001,
                y: 27
            },
            {
                x: 2002,
                y: 22
            },
            {
                x: 2003,
                y: 28
            },
            {
                x: 2004,
                y: 24
            },
            {
                x: 2005,
                y: 24
            }
        ]
    }
];

const MyResponsiveAreaBump = () => (
    <ResponsiveAreaBump
        data={data}
        startLabel
        endLabel
        margin={{ top: 40, right: 100, bottom: 40, left: 100 }}
        spacing={8}
        colors={{ scheme: 'pastel1' }}
        blendMode="multiply"

        defs={[
            {
                id: 'dots',
                type: 'patternDots',
                background: 'inherit',
                color: '#38bcb2',
                size: 4,
                padding: 1,
                stagger: true
            },
            {
                id: 'lines',
                type: 'patternLines',
                background: 'inherit',
                color: '#eed312',
                rotation: -45,
                lineWidth: 6,
                spacing: 10
            }
        ]}
        fill={[
            {
                match: {
                    id: 'CoffeeScript',

                },
                id: 'dots',
            },
            {
                match: {
                    id: 'TypeScript'
                },
                id: 'lines'
            }
        ]}
        axisTop={{
            tickSize: 5,
            tickPadding: 5,
            tickRotation: 0,
            legend: '',
            legendPosition: 'middle',
            legendOffset: -36
        }}
        axisBottom={{
            tickSize: 5,
            tickPadding: 5,
            tickRotation: 0,
            legend: '',
            legendPosition: 'middle',
            legendOffset: 32
        }}

    />
)


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
        <h1 className={styles.title}>
            Carte Boosté
        </h1>

          <div style={{ height: 300, width: 800 }}>
            <MyResponsiveAreaBump/>
          </div>


      </main>


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
